### ISSUE TITLE
Build for ZNC unstable / Master?

### ISSUE THREAD

**Issue by naphta** [znc/znc-docker#8]
I'd be interested in running the latest releases too, albeit even if they aren't marked stable. Any plans to do so?

**Comment by DarthGandalf** [comment]
Interesting idea.
This repo is for releases which go to https://hub.docker.com/_/znc/

According to https://docs.docker.com/docker-hub/builds/#create-an-automated-build Dockerfile would need to be in znc/znc repo. And its contents should be partially different, because it doesn't need (and can't) to download a tarball with the release.

**Comment by Delta1977** [comment]
how is the current state ?

**Comment by DarthGandalf** [comment]
@Delta1977 not done, obviously. Or what do you mean?

**Comment by naphta** [comment]
I might look into supporting a separate repository which does it. I've not got the time myself to do it but I'll put it on my back burner.

**Comment by DarthGandalf** [comment]
My current priorities are to release 1.7 ASAP. I might do this some time after releasing it, if you don't do it before.
